#!/bin/bash

if [ ! -d ~/.scripts ]; then
	mkdir ~/.scripts
fi

ln -s bspwmrc ~/.config/bspwm/bspwmrc 
ln -s sxhkdrc ~/.config/sxhkd/sxhkdrc
ln -s touchegg.conf ~/.config/touchegg/touchegg.conf
ln -s ghci ~/.ghci
ln -s tmux.conf ~/.tmux.conf
ln -s vimperatorrc ~/.vimperatorrc
ln -s vimrc ~/.vimrc
ln -s Xresources ~/.Xresources
ln -s zshrc ~/.zshrc
ln -s xinitrc ~/.xinitrc

ln -s scripts/touchpad.sh ~/.scripts/touchpad.sh
ln -s scripts/battery.sh ~/.scripts/battery.sh
ln -s scripts/net.sh ~/.scripts/net.sh
ln -s scripts/touchegg.sh ~/.scripts/touchegg.sh
